version: '3.8'
services:
  app:
    build: .
    expose:
      - "80"
  
  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
